import html
import re

from de_pipeline.schema import Diagnosis

MENTION = re.compile(r"@(?=[A-Za-z0-9])")


def render(diagnosis: Diagnosis) -> str:
    steps = "\n".join(
        f"{number}. {step}" for number, step in enumerate(diagnosis.fix_steps, start=1)
    )
    evidence = "\n\n".join(
        f"excerpt:\n{e.excerpt}\nexplanation: {e.explanation}"
        for e in diagnosis.evidence
    )

    rendered = f"""\n### SUMMARY ###\n{diagnosis.summary}\n### ROOT CAUSE ###\n{diagnosis.root_cause}\n### EVIDENCE ###\n{evidence}\n### SUGGESTED FIX (verify before applying) ###\n{steps}\n### CONFIDENCE ###\n{diagnosis.confidence}\n"""
    return rendered


def render_markdown(diagnosis: Diagnosis, run_url: str | None = None) -> str:
    lines = [
        f"### CI failure: {inline(diagnosis.summary)}",
        "",
        f"**Root cause:** {inline(diagnosis.root_cause)}",
        "",
        "**Suggested fix** (verify before applying):",
        "",
    ]
    lines += [f"{n}. {inline(step)}" for n, step in enumerate(diagnosis.fix_steps, start=1)]
    lines += ["", "<details><summary>Evidence</summary>", ""]
    for item in diagnosis.evidence:
        lines += [code_block(item.excerpt), "", inline(item.explanation), ""]
    lines += ["</details>", "", f"Confidence: **{diagnosis.confidence}**"]
    if run_url:
        lines += ["", f"[View the failed run]({run_url})"]
    lines += ["", "<sub>Generated by de-pipeline. AI-generated analysis; verify before acting on it.</sub>"]
    return "\n".join(lines)


def inline(value: str) -> str:
    escaped = html.escape(" ".join(value.split()), quote=False)
    return MENTION.sub("@\u200b", escaped)


def code_block(content: str) -> str:
    fence = "```"
    while fence in content:
        fence += "`"
    return f"{fence}\n{content}\n{fence}"